using System;
using System.Collections.Generic; // Required for IReadOnlyDictionary in .NET Standard 2.0

namespace AspectWeaver.Abstractions
{
    /// <summary>
    /// Provides context information about the intercepted method invocation.
    /// This context is passed through the chain of aspect handlers.
    /// </summary>
    public sealed class InvocationContext
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InvocationContext"/> class.
        /// </summary>
        /// <remarks>
        /// This constructor is intended to be called by the code generated by AspectWeaver.
        /// </remarks>
        public InvocationContext(
            object? targetInstance,
            IServiceProvider serviceProvider,
            string methodName,
            string targetTypeName,
            IReadOnlyDictionary<string, object?> arguments)
        {
            // Enforce invariants: these properties are essential and must not be null.
            // We use standard null checks for .NET Standard 2.0 compatibility and performance.
            ServiceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
            MethodName = methodName ?? throw new ArgumentNullException(nameof(methodName));
            TargetTypeName = targetTypeName ?? throw new ArgumentNullException(nameof(targetTypeName));
            Arguments = arguments ?? throw new ArgumentNullException(nameof(arguments));
            TargetInstance = targetInstance;
        }

        #region PBI 1.3 - Core Properties and Environment

        /// <summary>
        /// Gets the instance of the object on which the method is being invoked.
        /// Returns null if the intercepted method is static.
        /// </summary>
        public object? TargetInstance { get; }

        /// <summary>
        /// Gets the <see cref="IServiceProvider"/> associated with the current execution scope.
        /// This allows aspect handlers to resolve dependencies.
        /// </summary>
        public IServiceProvider ServiceProvider { get; }

        /// <summary>
        /// Gets the name of the intercepted method.
        /// </summary>
        public string MethodName { get; }

        /// <summary>
        /// Gets the full name of the type containing the intercepted method.
        /// </summary>
        public string TargetTypeName { get; }

        // Note: We explicitly avoid exposing System.Reflection.MethodInfo
        // to adhere to the zero-overhead principle (prevent runtime reflection).

        #endregion

        #region PBI 1.4 - Argument Access

        /// <summary>
        /// Gets a read-only dictionary containing the arguments passed to the intercepted method.
        /// The keys are the parameter names, and the values are the argument values.
        /// </summary>
        /// <remarks>
        /// // TODO: Post-MVP Optimization: Implement zero-allocation argument access (e.g., using a struct-based accessor).
        /// Currently, this MVP implementation may cause boxing for value types.
        /// </remarks>
        public IReadOnlyDictionary<string, object?> Arguments { get; }

        #endregion
    }
}