namespace Aymen83.AspectWeaver.Generator
{
    /// <summary>
    /// Contains constant strings for C# source code templates used in generation.
    /// </summary>
    internal static class SourceTemplates
    {
        public const string InterceptsLocationAttributeSource = """
// <auto-generated>
// This file is generated by AspectWeaver.
// It defines the necessary attributes for C# 12 Interceptors.
// </auto-generated>

#nullable enable

namespace System.Runtime.CompilerServices
{
    using System;

    /// <summary>
    /// Allows a C# compiler to redirect an invocation to a different method (Interceptor).
    /// Note: This attribute must be defined internally as it is recognized intrinsically by the compiler.
    /// </summary>
    [global::System.Diagnostics.Conditional("DEBUG")]
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
    internal sealed class InterceptsLocationAttribute : Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InterceptsLocationAttribute"/> class.
        /// </summary>
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}
""";
    }
}