//HintName: AspectWeaver.Interceptors.g.cs
// <auto-generated>
// This file was generated by Aymen83.AspectWeaver. DO NOT EDIT.
// </auto-generated>

#nullable enable

#pragma warning disable CS1591
#pragma warning disable RS0016

using System.Runtime.CompilerServices;
using System.Diagnostics;
using System.Reflection;

namespace Aymen83.AspectWeaver.Generated
{
    [global::System.Diagnostics.DebuggerStepThrough]
    [global::System.Diagnostics.DebuggerNonUserCode]
    internal static class Interceptors
    {
        [global::System.Runtime.CompilerServices.InterceptsLocation(version: 1, data: "[ScrubbedData]")]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static int InterceptMethod0(this global::TestApp.FeatureService __instance, in int factor, params int[] values)
        {
            // 1. Resolve IServiceProvider
            global::System.IServiceProvider __serviceProvider = __instance.ServiceProvider;
            if (__serviceProvider == null) throw new global::System.InvalidOperationException("The IServiceProvider accessed via '__instance.ServiceProvider' returned null. Ensure the provider is correctly initialized on the instance.");
            
            // 2. Create InvocationContext
            var __arguments = new Interceptor0_Cache.ArgumentsStruct(factor, values);
            var __context = new global::Aymen83.AspectWeaver.Abstractions.InvocationContext(
                targetInstance: __instance,
                serviceProvider: __serviceProvider,
                methodInfo: Interceptor0_Cache.MethodInfo,
                methodName: "CalculateSum",
                targetTypeName: "global::TestApp.FeatureService",
                arguments: __arguments
            );
            
            // 3. Core: The original method call.
            global::System.Func<global::Aymen83.AspectWeaver.Abstractions.InvocationContext, global::System.Threading.Tasks.ValueTask<int>> __pipeline = (ctx) =>
            {
                var result = __instance.CalculateSum(factor, values);
                return new global::System.Threading.Tasks.ValueTask<int>(result);
            };
            
            // 4. Wrapping: Apply aspects (from inner to outer).
            // Aspect 0: global::AspectAAttribute (Order=10)
            var __next0 = __pipeline;
            var __handler0 = (global::Aymen83.AspectWeaver.Abstractions.IAspectHandler<global::AspectAAttribute>?)__serviceProvider.GetService(typeof(global::Aymen83.AspectWeaver.Abstractions.IAspectHandler<global::AspectAAttribute>));
            if (__handler0 == null) throw new global::System.InvalidOperationException("Handler not registered for aspect: global::AspectAAttribute");
            var __attribute0 = Interceptor0_Cache.Attribute_0;
            __pipeline = (ctx) =>
            {
                return __handler0.InterceptAsync<int>(__attribute0, ctx, __next0);
            };
            
            // 5. Execute the pipeline.
            // Execution Mode: Synchronous.
            var __finalResult = __pipeline(__context).GetAwaiter().GetResult();
            return __finalResult;
        }
        
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Diagnostics.DebuggerNonUserCode]
        private static class Interceptor0_Cache
        {
            public readonly struct ArgumentsStruct : global::Aymen83.AspectWeaver.Abstractions.IArgumentsContainer
            {
                private readonly global::System.Int32 _factor;
                private readonly global::System.Int32[] _values;
                
                public ArgumentsStruct(global::System.Int32 factor, global::System.Int32[] values)
                {
                    _factor = factor;
                    _values = values;
                }
                
                public int Count => 2;
                
                public object? this[string parameterName] => parameterName switch
                {
                    "factor" => _factor,
                    "values" => _values,
                    _ => throw new global::System.ArgumentOutOfRangeException(nameof(parameterName), $"Parameter '{parameterName}' not found.")
                };
                
                public global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>> GetEnumerator()
                {
                    yield return new global::System.Collections.Generic.KeyValuePair<string, object?>("factor", _factor);
                    yield return new global::System.Collections.Generic.KeyValuePair<string, object?>("values", _values);
                }
                
                global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
            }
            
            internal static readonly MethodInfo MethodInfo = InitMethodInfo();
            
            internal static readonly global::AspectAAttribute Attribute_0 = InitAttribute_0();
            
            private static global::AspectAAttribute InitAttribute_0()
            {
                return new global::AspectAAttribute();
            }
            
            private static MethodInfo InitMethodInfo()
            {
                var __targetType = typeof(global::TestApp.FeatureService);
                var __paramTypes = new global::System.Type[]
                {
                    typeof(int).MakeByRefType(),
                    typeof(int[]),
                };
                var methodInfo = __targetType.GetMethod("CalculateSum", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance, null, __paramTypes, null);
                if (methodInfo == null) throw new global::System.InvalidOperationException("Could not resolve MethodInfo for CalculateSum during initialization.");
                return methodInfo;
            }
            
        }
        
        [global::System.Runtime.CompilerServices.InterceptsLocation(version: 1, data: "[ScrubbedData]")]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static int InterceptMethod1(this global::TestApp.FeatureService __instance, in int factor, params int[] values)
        {
            // 1. Resolve IServiceProvider
            global::System.IServiceProvider __serviceProvider = __instance.ServiceProvider;
            if (__serviceProvider == null) throw new global::System.InvalidOperationException("The IServiceProvider accessed via '__instance.ServiceProvider' returned null. Ensure the provider is correctly initialized on the instance.");
            
            // 2. Create InvocationContext
            var __arguments = new Interceptor1_Cache.ArgumentsStruct(factor, values);
            var __context = new global::Aymen83.AspectWeaver.Abstractions.InvocationContext(
                targetInstance: __instance,
                serviceProvider: __serviceProvider,
                methodInfo: Interceptor1_Cache.MethodInfo,
                methodName: "CalculateSum",
                targetTypeName: "global::TestApp.FeatureService",
                arguments: __arguments
            );
            
            // 3. Core: The original method call.
            global::System.Func<global::Aymen83.AspectWeaver.Abstractions.InvocationContext, global::System.Threading.Tasks.ValueTask<int>> __pipeline = (ctx) =>
            {
                var result = __instance.CalculateSum(factor, values);
                return new global::System.Threading.Tasks.ValueTask<int>(result);
            };
            
            // 4. Wrapping: Apply aspects (from inner to outer).
            // Aspect 0: global::AspectAAttribute (Order=10)
            var __next0 = __pipeline;
            var __handler0 = (global::Aymen83.AspectWeaver.Abstractions.IAspectHandler<global::AspectAAttribute>?)__serviceProvider.GetService(typeof(global::Aymen83.AspectWeaver.Abstractions.IAspectHandler<global::AspectAAttribute>));
            if (__handler0 == null) throw new global::System.InvalidOperationException("Handler not registered for aspect: global::AspectAAttribute");
            var __attribute0 = Interceptor1_Cache.Attribute_0;
            __pipeline = (ctx) =>
            {
                return __handler0.InterceptAsync<int>(__attribute0, ctx, __next0);
            };
            
            // 5. Execute the pipeline.
            // Execution Mode: Synchronous.
            var __finalResult = __pipeline(__context).GetAwaiter().GetResult();
            return __finalResult;
        }
        
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Diagnostics.DebuggerNonUserCode]
        private static class Interceptor1_Cache
        {
            public readonly struct ArgumentsStruct : global::Aymen83.AspectWeaver.Abstractions.IArgumentsContainer
            {
                private readonly global::System.Int32 _factor;
                private readonly global::System.Int32[] _values;
                
                public ArgumentsStruct(global::System.Int32 factor, global::System.Int32[] values)
                {
                    _factor = factor;
                    _values = values;
                }
                
                public int Count => 2;
                
                public object? this[string parameterName] => parameterName switch
                {
                    "factor" => _factor,
                    "values" => _values,
                    _ => throw new global::System.ArgumentOutOfRangeException(nameof(parameterName), $"Parameter '{parameterName}' not found.")
                };
                
                public global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>> GetEnumerator()
                {
                    yield return new global::System.Collections.Generic.KeyValuePair<string, object?>("factor", _factor);
                    yield return new global::System.Collections.Generic.KeyValuePair<string, object?>("values", _values);
                }
                
                global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
            }
            
            internal static readonly MethodInfo MethodInfo = InitMethodInfo();
            
            internal static readonly global::AspectAAttribute Attribute_0 = InitAttribute_0();
            
            private static global::AspectAAttribute InitAttribute_0()
            {
                return new global::AspectAAttribute();
            }
            
            private static MethodInfo InitMethodInfo()
            {
                var __targetType = typeof(global::TestApp.FeatureService);
                var __paramTypes = new global::System.Type[]
                {
                    typeof(int).MakeByRefType(),
                    typeof(int[]),
                };
                var methodInfo = __targetType.GetMethod("CalculateSum", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance, null, __paramTypes, null);
                if (methodInfo == null) throw new global::System.InvalidOperationException("Could not resolve MethodInfo for CalculateSum during initialization.");
                return methodInfo;
            }
            
        }
    }
}
