//HintName: AspectWeaver.Interceptors.g.cs
// <auto-generated>
// This file was generated by Aymen83.AspectWeaver. DO NOT EDIT.
// </auto-generated>

#nullable enable

#pragma warning disable CS1591
#pragma warning disable RS0016

using System.Runtime.CompilerServices;
using System.Diagnostics;
using System.Reflection;

namespace Aymen83.AspectWeaver.Generated
{
    [global::System.Diagnostics.DebuggerStepThrough]
    [global::System.Diagnostics.DebuggerNonUserCode]
    internal static class Interceptors
    {
        [global::System.Runtime.CompilerServices.InterceptsLocation(version: 1, data: "[ScrubbedData]")]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static bool InterceptMethod0(this global::TestApp.ComplexService __instance, string input, out int value, ref bool initialized)
        {
            // 1. Resolve IServiceProvider
            global::System.IServiceProvider __serviceProvider = __instance.ServiceProvider;
            if (__serviceProvider == null) throw new global::System.InvalidOperationException("The IServiceProvider accessed via '__instance.ServiceProvider' returned null. Ensure the provider is correctly initialized on the instance.");
            
            // 2. Create InvocationContext
            var __arguments = new Interceptor0_Cache.ArgumentsStruct(input, value, initialized);
            var __context = new global::Aymen83.AspectWeaver.Abstractions.InvocationContext(
                targetInstance: __instance,
                serviceProvider: __serviceProvider,
                methodInfo: Interceptor0_Cache.MethodInfo,
                methodName: "TryParse",
                targetTypeName: "global::TestApp.ComplexService",
                arguments: __arguments
            );
            
            // 3. Core: The original method call.
            global::System.Func<global::Aymen83.AspectWeaver.Abstractions.InvocationContext, global::System.Threading.Tasks.ValueTask<bool>> __pipeline = (ctx) =>
            {
                var result = __instance.TryParse(input, out value, ref initialized);
                return new global::System.Threading.Tasks.ValueTask<bool>(result);
            };
            
            // 4. Wrapping: Apply aspects (from inner to outer).
            // Aspect 0: global::RefOutAspectAttribute (Order=0)
            var __next0 = __pipeline;
            var __handler0 = (global::Aymen83.AspectWeaver.Abstractions.IAspectHandler<global::RefOutAspectAttribute>?)__serviceProvider.GetService(typeof(global::Aymen83.AspectWeaver.Abstractions.IAspectHandler<global::RefOutAspectAttribute>));
            if (__handler0 == null) throw new global::System.InvalidOperationException("Handler not registered for aspect: global::RefOutAspectAttribute");
            var __attribute0 = Interceptor0_Cache.Attribute_0;
            __pipeline = (ctx) =>
            {
                return __handler0.InterceptAsync<bool>(__attribute0, ctx, __next0);
            };
            
            // 5. Execute the pipeline.
            // Execution Mode: Synchronous.
            var __finalResult = __pipeline(__context).GetAwaiter().GetResult();
            return __finalResult;
        }
        
        [global::System.Diagnostics.DebuggerStepThrough]
        [global::System.Diagnostics.DebuggerNonUserCode]
        private static class Interceptor0_Cache
        {
            public readonly struct ArgumentsStruct : global::Aymen83.AspectWeaver.Abstractions.IArgumentsContainer
            {
                private readonly global::System.String _input;
                private readonly global::System.Int32 _value;
                private readonly global::System.Boolean _initialized;
                
                public ArgumentsStruct(global::System.String input, global::System.Int32 value, global::System.Boolean initialized)
                {
                    _input = input;
                    _value = value;
                    _initialized = initialized;
                }
                
                public int Count => 3;
                
                public object? this[string parameterName] => parameterName switch
                {
                    "input" => _input,
                    "value" => _value,
                    "initialized" => _initialized,
                    _ => throw new global::System.ArgumentOutOfRangeException(nameof(parameterName), $"Parameter '{parameterName}' not found.")
                };
                
                public global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<string, object?>> GetEnumerator()
                {
                    yield return new global::System.Collections.Generic.KeyValuePair<string, object?>("input", _input);
                    yield return new global::System.Collections.Generic.KeyValuePair<string, object?>("value", _value);
                    yield return new global::System.Collections.Generic.KeyValuePair<string, object?>("initialized", _initialized);
                }
                
                global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();
            }
            
            internal static readonly MethodInfo MethodInfo = InitMethodInfo();
            
            internal static readonly global::RefOutAspectAttribute Attribute_0 = InitAttribute_0();
            
            private static global::RefOutAspectAttribute InitAttribute_0()
            {
                return new global::RefOutAspectAttribute();
            }
            
            private static MethodInfo InitMethodInfo()
            {
                var __targetType = typeof(global::TestApp.ComplexService);
                var __paramTypes = new global::System.Type[]
                {
                    typeof(string),
                    typeof(int).MakeByRefType(),
                    typeof(bool).MakeByRefType(),
                };
                var methodInfo = __targetType.GetMethod("TryParse", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance, null, __paramTypes, null);
                if (methodInfo == null) throw new global::System.InvalidOperationException("Could not resolve MethodInfo for TryParse during initialization.");
                return methodInfo;
            }
            
        }
    }
}
