//HintName: AspectWeaver.Interceptors.g.cs
// <auto-generated>
// This file was generated by AspectWeaver. DO NOT EDIT.
// </auto-generated>

#nullable enable

using System.Runtime.CompilerServices;

namespace AspectWeaver.Generated
{
    internal static class Interceptors
    {
        [InterceptsLocation("[ScrubbedPath]", 21, 21)]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static void InterceptMethod0(this global::TestApp.MyService __instance)
        {
            // 1. Resolve IServiceProvider
            global::System.IServiceProvider __serviceProvider = __instance._serviceProvider;
            if (__serviceProvider == null) throw new global::System.InvalidOperationException("The IServiceProvider accessed via '__instance._serviceProvider' returned null. Ensure the provider is correctly initialized on the instance.");
            
            // 2. Create InvocationContext
            // PBI 4.2: Resolve MethodInfo (Using Type.GetMethod for robustness).
            var __targetType = typeof(global::TestApp.MyService);
            var __paramTypes = new global::System.Type[]
            {
            };
            var __methodInfo = __targetType.GetMethod("DoWork", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, __paramTypes, null);
            if (__methodInfo == null) throw new global::System.InvalidOperationException("Could not resolve MethodInfo for DoWork. This indicates an issue in AspectWeaver.");
            var __arguments = new global::System.Collections.Generic.Dictionary<string, object?>()
            {
            };
            var __context = new global::AspectWeaver.Abstractions.InvocationContext(
                targetInstance: __instance,
                serviceProvider: __serviceProvider,
                methodInfo: __methodInfo,
                methodName: "DoWork",
                targetTypeName: "global::TestApp.MyService",
                arguments: __arguments
            );
            
            // 3. Core: The original method call.
            global::System.Func<global::AspectWeaver.Abstractions.InvocationContext, global::System.Threading.Tasks.ValueTask<global::AspectWeaver.Abstractions.VoidResult>> __pipeline = (ctx) =>
            {
                __instance.DoWork();
                return new global::System.Threading.Tasks.ValueTask<global::AspectWeaver.Abstractions.VoidResult>(global::AspectWeaver.Abstractions.VoidResult.Instance);
            };
            
            // 4. Wrapping: Apply aspects (from inner to outer).
            // Aspect 0: global::DIAttribute (Order=0)
            var __next0 = __pipeline;
            var __handler0 = (global::AspectWeaver.Abstractions.IAspectHandler<global::DIAttribute>?)__serviceProvider.GetService(typeof(global::AspectWeaver.Abstractions.IAspectHandler<global::DIAttribute>));
            if (__handler0 == null) throw new global::System.InvalidOperationException("Handler not registered for aspect: global::DIAttribute");
            var __attribute0 = new global::DIAttribute();
            __pipeline = (ctx) =>
            {
                return __handler0.InterceptAsync<global::AspectWeaver.Abstractions.VoidResult>(__attribute0, ctx, __next0);
            };
            
            // 5. Execute the pipeline.
            // Execution Mode: Synchronous.
            var __finalResult = __pipeline(__context).GetAwaiter().GetResult();
        }
    }
}
