//HintName: AspectWeaver.Interceptors.g.cs
// <auto-generated>
// This file was generated by AspectWeaver. DO NOT EDIT.
// </auto-generated>

#nullable enable

using System.Runtime.CompilerServices;

namespace AspectWeaver.Generated
{
    internal static class Interceptors
    {
        [InterceptsLocation("[ScrubbedPath]", 63, 20)]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static void InterceptMethod0(this global::TestApp.ConcreteWorker __instance)
        {
            // 1. Resolve IServiceProvider
            global::System.IServiceProvider __serviceProvider = __instance.ServiceProvider;
            if (__serviceProvider == null) throw new global::System.InvalidOperationException("The IServiceProvider accessed via '__instance.ServiceProvider' returned null. Ensure the provider is correctly initialized on the instance.");
            
            // 2. Create InvocationContext
            // PBI 4.2: Resolve MethodInfo (Using Type.GetMethod for robustness).
            var __targetType = typeof(global::TestApp.ConcreteWorker);
            var __paramTypes = new global::System.Type[]
            {
            };
            var __methodInfo = __targetType.GetMethod("Work", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, __paramTypes, null);
            if (__methodInfo == null) throw new global::System.InvalidOperationException("Could not resolve MethodInfo for Work. This indicates an issue in AspectWeaver.");
            var __arguments = new global::System.Collections.Generic.Dictionary<string, object?>()
            {
            };
            var __context = new global::AspectWeaver.Abstractions.InvocationContext(
                targetInstance: __instance,
                serviceProvider: __serviceProvider,
                methodInfo: __methodInfo,
                methodName: "Work",
                targetTypeName: "global::TestApp.ConcreteWorker",
                arguments: __arguments
            );
            
            // 3. Core: The original method call.
            global::System.Func<global::AspectWeaver.Abstractions.InvocationContext, global::System.Threading.Tasks.ValueTask<global::AspectWeaver.Abstractions.VoidResult>> __pipeline = (ctx) =>
            {
                __instance.Work();
                return new global::System.Threading.Tasks.ValueTask<global::AspectWeaver.Abstractions.VoidResult>(global::AspectWeaver.Abstractions.VoidResult.Instance);
            };
            
            // 4. Wrapping: Apply aspects (from inner to outer).
            // Aspect 3: global::AspectBAttribute (Order=20)
            var __next3 = __pipeline;
            var __handler3 = (global::AspectWeaver.Abstractions.IAspectHandler<global::AspectBAttribute>?)__serviceProvider.GetService(typeof(global::AspectWeaver.Abstractions.IAspectHandler<global::AspectBAttribute>));
            if (__handler3 == null) throw new global::System.InvalidOperationException("Handler not registered for aspect: global::AspectBAttribute");
            var __attribute3 = new global::AspectBAttribute();
            __pipeline = (ctx) =>
            {
                return __handler3.InterceptAsync<global::AspectWeaver.Abstractions.VoidResult>(__attribute3, ctx, __next3);
            };
            
            // Aspect 2: global::AspectAAttribute (Order=10)
            var __next2 = __pipeline;
            var __handler2 = (global::AspectWeaver.Abstractions.IAspectHandler<global::AspectAAttribute>?)__serviceProvider.GetService(typeof(global::AspectWeaver.Abstractions.IAspectHandler<global::AspectAAttribute>));
            if (__handler2 == null) throw new global::System.InvalidOperationException("Handler not registered for aspect: global::AspectAAttribute");
            var __attribute2 = new global::AspectAAttribute();
            __pipeline = (ctx) =>
            {
                return __handler2.InterceptAsync<global::AspectWeaver.Abstractions.VoidResult>(__attribute2, ctx, __next2);
            };
            
            // Aspect 1: global::AspectCAttribute (Order=5)
            var __next1 = __pipeline;
            var __handler1 = (global::AspectWeaver.Abstractions.IAspectHandler<global::AspectCAttribute>?)__serviceProvider.GetService(typeof(global::AspectWeaver.Abstractions.IAspectHandler<global::AspectCAttribute>));
            if (__handler1 == null) throw new global::System.InvalidOperationException("Handler not registered for aspect: global::AspectCAttribute");
            var __attribute1 = new global::AspectCAttribute();
            __pipeline = (ctx) =>
            {
                return __handler1.InterceptAsync<global::AspectWeaver.Abstractions.VoidResult>(__attribute1, ctx, __next1);
            };
            
            // Aspect 0: global::UniqueAspectAttribute (Order=1)
            var __next0 = __pipeline;
            var __handler0 = (global::AspectWeaver.Abstractions.IAspectHandler<global::UniqueAspectAttribute>?)__serviceProvider.GetService(typeof(global::AspectWeaver.Abstractions.IAspectHandler<global::UniqueAspectAttribute>));
            if (__handler0 == null) throw new global::System.InvalidOperationException("Handler not registered for aspect: global::UniqueAspectAttribute");
            var __attribute0 = new global::UniqueAspectAttribute();
            __pipeline = (ctx) =>
            {
                return __handler0.InterceptAsync<global::AspectWeaver.Abstractions.VoidResult>(__attribute0, ctx, __next0);
            };
            
            // 5. Execute the pipeline.
            // Execution Mode: Synchronous.
            var __finalResult = __pipeline(__context).GetAwaiter().GetResult();
        }
        
        [InterceptsLocation("[ScrubbedPath]", 67, 21)]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static void InterceptMethod1(this global::TestApp.IWorker __instance)
        {
            // 1. Resolve IServiceProvider
            global::System.IServiceProvider __serviceProvider = __instance.ServiceProvider;
            if (__serviceProvider == null) throw new global::System.InvalidOperationException("The IServiceProvider accessed via '__instance.ServiceProvider' returned null. Ensure the provider is correctly initialized on the instance.");
            
            // 2. Create InvocationContext
            // PBI 4.2: Resolve MethodInfo (Using Type.GetMethod for robustness).
            var __targetType = typeof(global::TestApp.IWorker);
            var __paramTypes = new global::System.Type[]
            {
            };
            var __methodInfo = __targetType.GetMethod("Work", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, __paramTypes, null);
            if (__methodInfo == null) throw new global::System.InvalidOperationException("Could not resolve MethodInfo for Work. This indicates an issue in AspectWeaver.");
            var __arguments = new global::System.Collections.Generic.Dictionary<string, object?>()
            {
            };
            var __context = new global::AspectWeaver.Abstractions.InvocationContext(
                targetInstance: __instance,
                serviceProvider: __serviceProvider,
                methodInfo: __methodInfo,
                methodName: "Work",
                targetTypeName: "global::TestApp.IWorker",
                arguments: __arguments
            );
            
            // 3. Core: The original method call.
            global::System.Func<global::AspectWeaver.Abstractions.InvocationContext, global::System.Threading.Tasks.ValueTask<global::AspectWeaver.Abstractions.VoidResult>> __pipeline = (ctx) =>
            {
                __instance.Work();
                return new global::System.Threading.Tasks.ValueTask<global::AspectWeaver.Abstractions.VoidResult>(global::AspectWeaver.Abstractions.VoidResult.Instance);
            };
            
            // 4. Wrapping: Apply aspects (from inner to outer).
            // Aspect 1: global::AspectAAttribute (Order=10)
            var __next1 = __pipeline;
            var __handler1 = (global::AspectWeaver.Abstractions.IAspectHandler<global::AspectAAttribute>?)__serviceProvider.GetService(typeof(global::AspectWeaver.Abstractions.IAspectHandler<global::AspectAAttribute>));
            if (__handler1 == null) throw new global::System.InvalidOperationException("Handler not registered for aspect: global::AspectAAttribute");
            var __attribute1 = new global::AspectAAttribute();
            __pipeline = (ctx) =>
            {
                return __handler1.InterceptAsync<global::AspectWeaver.Abstractions.VoidResult>(__attribute1, ctx, __next1);
            };
            
            // Aspect 0: global::UniqueAspectAttribute (Order=1)
            var __next0 = __pipeline;
            var __handler0 = (global::AspectWeaver.Abstractions.IAspectHandler<global::UniqueAspectAttribute>?)__serviceProvider.GetService(typeof(global::AspectWeaver.Abstractions.IAspectHandler<global::UniqueAspectAttribute>));
            if (__handler0 == null) throw new global::System.InvalidOperationException("Handler not registered for aspect: global::UniqueAspectAttribute");
            var __attribute0 = new global::UniqueAspectAttribute();
            __pipeline = (ctx) =>
            {
                return __handler0.InterceptAsync<global::AspectWeaver.Abstractions.VoidResult>(__attribute0, ctx, __next0);
            };
            
            // 5. Execute the pipeline.
            // Execution Mode: Synchronous.
            var __finalResult = __pipeline(__context).GetAwaiter().GetResult();
        }
    }
}
