//HintName: PlaceholderServiceProvider.g.cs
// <auto-generated>
// Placeholder for IServiceProvider used until DI integration is configured (Epic 3).
// </auto-generated>

#nullable enable

namespace AspectWeaver.Generated
{
    using System;

    internal sealed class PlaceholderServiceProvider : IServiceProvider
    {
        // For the MVP PBI 2.5, we return null. The generated pipeline code checks for null and throws.
        // This correctly simulates a missing DI registration without complex placeholder logic.
        public object? GetService(Type serviceType)
        {
            return null;
        }
    }
}