//HintName: AspectWeaver.Interceptors.g.cs
// <auto-generated>
// This file was generated by AspectWeaver. DO NOT EDIT.
// </auto-generated>

#nullable enable

using System.Runtime.CompilerServices;

namespace AspectWeaver.Generated
{
    internal static class Interceptors
    {
        [InterceptsLocation("[ScrubbedPath]", 25, 40)]
        internal static async global::System.Threading.Tasks.Task<int> InterceptMethod0(this global::TestApp.AsyncService __instance)
        {
            // 1. Resolve IServiceProvider (Placeholder for Epic 3)
            global::System.IServiceProvider __serviceProvider = new global::AspectWeaver.Generated.PlaceholderServiceProvider();
            
            // 2. Create InvocationContext
            var __arguments = new global::System.Collections.Generic.Dictionary<string, object?>()
            {
            };
            var __context = new global::AspectWeaver.Abstractions.InvocationContext(
                targetInstance: __instance,
                serviceProvider: __serviceProvider,
                methodName: "CalculateAsync",
                targetTypeName: "global::TestApp.AsyncService",
                arguments: __arguments
            );
            
            // 3. Core: The original method call.
            global::System.Func<global::AspectWeaver.Abstractions.InvocationContext, global::System.Threading.Tasks.ValueTask<int>> __pipeline = async (ctx) =>
            {
                var result = await __instance.CalculateAsync().ConfigureAwait(false);
                return result;
            };
            
            // 4. Wrapping: Apply aspects (from inner to outer).
            // Aspect 0: global::AsyncAspectAttribute (Order=5)
            var __next0 = __pipeline;
            var __handler0 = (global::AspectWeaver.Abstractions.IAspectHandler<global::AsyncAspectAttribute>)__serviceProvider.GetService(typeof(global::AspectWeaver.Abstractions.IAspectHandler<global::AsyncAspectAttribute>));
            if (__handler0 == null) throw new global::System.InvalidOperationException("Handler not registered for aspect: global::AsyncAspectAttribute");
            var __attribute0 = new global::AsyncAspectAttribute("ConfigValue")
            {
                Order = 5
            };
            __pipeline = (ctx) =>
            {
                return __handler0.InterceptAsync<int>(__attribute0, ctx, __next0);
            };
            
            // 5. Execute the pipeline.
            // Execution Mode: Asynchronous.
            var __finalResult = await __pipeline(__context).ConfigureAwait(false);
            return __finalResult;
        }
    }
}
