//HintName: AspectWeaver.Interceptors.g.cs
// <auto-generated>
// This file was generated by AspectWeaver. DO NOT EDIT.
// </auto-generated>

#nullable enable

using System.Runtime.CompilerServices;

namespace AspectWeaver.Generated
{
    internal static class Interceptors
    {
        [InterceptsLocation("[ScrubbedPath]", 29, 27)]
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static async global::System.Threading.Tasks.ValueTask InterceptMethod0(this global::TestApp.AsyncService __instance)
        {
            // 1. Resolve IServiceProvider
            global::System.IServiceProvider __serviceProvider = __instance.ServiceProvider;
            if (__serviceProvider == null) throw new global::System.InvalidOperationException("The IServiceProvider accessed via '__instance.ServiceProvider' returned null. Ensure the provider is correctly initialized on the instance.");
            
            // 2. Create InvocationContext
            // PBI 4.2: Resolve MethodInfo (Using Type.GetMethod for robustness).
            var __targetType = typeof(global::TestApp.AsyncService);
            var __paramTypes = new global::System.Type[]
            {
            };
            var __methodInfo = __targetType.GetMethod("DoWorkValueAsync", global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, __paramTypes, null);
            if (__methodInfo == null) throw new global::System.InvalidOperationException("Could not resolve MethodInfo for DoWorkValueAsync. This indicates an issue in AspectWeaver.");
            var __arguments = new global::System.Collections.Generic.Dictionary<string, object?>()
            {
            };
            var __context = new global::AspectWeaver.Abstractions.InvocationContext(
                targetInstance: __instance,
                serviceProvider: __serviceProvider,
                methodInfo: __methodInfo,
                methodName: "DoWorkValueAsync",
                targetTypeName: "global::TestApp.AsyncService",
                arguments: __arguments
            );
            
            // 3. Core: The original method call.
            global::System.Func<global::AspectWeaver.Abstractions.InvocationContext, global::System.Threading.Tasks.ValueTask<global::AspectWeaver.Abstractions.VoidResult>> __pipeline = async (ctx) =>
            {
                await __instance.DoWorkValueAsync().ConfigureAwait(false);
                return global::AspectWeaver.Abstractions.VoidResult.Instance;
            };
            
            // 4. Wrapping: Apply aspects (from inner to outer).
            // Aspect 0: global::AsyncAspectAttribute (Order=0)
            var __next0 = __pipeline;
            var __handler0 = (global::AspectWeaver.Abstractions.IAspectHandler<global::AsyncAspectAttribute>?)__serviceProvider.GetService(typeof(global::AspectWeaver.Abstractions.IAspectHandler<global::AsyncAspectAttribute>));
            if (__handler0 == null) throw new global::System.InvalidOperationException("Handler not registered for aspect: global::AsyncAspectAttribute");
            var __attribute0 = new global::AsyncAspectAttribute();
            __pipeline = (ctx) =>
            {
                return __handler0.InterceptAsync<global::AspectWeaver.Abstractions.VoidResult>(__attribute0, ctx, __next0);
            };
            
            // 5. Execute the pipeline.
            // Execution Mode: Asynchronous.
            var __finalResult = await __pipeline(__context).ConfigureAwait(false);
        }
    }
}
