// src/AspectWeaver.Generator/Emitters/IndentedWriter.cs
using System;
using System.CodeDom.Compiler;
using System.IO;
using System.Text;

namespace AspectWeaver.Generator.Emitters
{
    /// <summary>
    /// Helper class to facilitate clean, indented C# code generation.
    /// </summary>
    internal sealed class IndentedWriter : IDisposable
    {
        // ... (Fields and constructor remain the same)
        private readonly StringBuilder _sb;
        private readonly StringWriter _sw;
        private readonly IndentedTextWriter _writer;

        public IndentedWriter()
        {
            _sb = new StringBuilder();
            _sw = new StringWriter(_sb);
            // Use 4 spaces for indentation.
            _writer = new IndentedTextWriter(_sw, "    ");
        }

        // ... (Write methods, Indent/Outdent, OpenBlock/CloseBlock, ToString, Dispose remain the same)
        public void Write(string s) => _writer.Write(s);
        public void WriteLine(string s) => _writer.WriteLine(s);
        public void WriteLine() => _writer.WriteLine();

        public void Indent() => _writer.Indent++;
        public void Outdent() => _writer.Indent--;

        public void OpenBlock()
        {
            WriteLine("{");
            Indent();
        }

        public void CloseBlock(string suffix = "")
        {
            Outdent();
            WriteLine("}" + suffix);
        }

        public override string ToString() => _sb.ToString();


        public void WriteFileHeader()
        {
            WriteLine("// <auto-generated>");
            WriteLine("// This file was generated by AspectWeaver. DO NOT EDIT.");
            WriteLine("// </auto-generated>");
            WriteLine();
            WriteLine("#nullable enable");
            WriteLine();
            // PBI 5.3: Add pragmas to suppress warnings in generated code.
            WriteLine("// Suppress warnings for generated code.");
            // CS1591: Missing XML comment for publicly visible type or member.
            WriteLine("#pragma warning disable CS1591");
            // RS0016: Add public types and members to the declared API (Common in generated infrastructure).
            WriteLine("#pragma warning disable RS0016");
            WriteLine();
        }

        public void Dispose()
        {
            _writer.Dispose();
            _sw.Dispose();
        }
    }
}